### ISSUE TITLE
 ARM External triggering 

### ISSUE THREAD

**Issue by NathanHarrington** [WasatchPhotonics/WasatchUSB#2]
Create a simple test script that tests just the ARM triggering functionality according to the following procedure:

Hook up physical connections according to PRD83
ARM board on
collect internally triggered spectra

external trigger on
wait until usb time out
make sure no spectra were collected.

External trigger on
do not send 0xad for command get image
burst trigger (1)
ensure exactly 1 spectra was collected

External trigger on
do not send 0xad for command get image
burst trigger (10)
ensure exactly 10 spectra was collected

This is for what appears to be the first of it's kind ARM silicon cube, WP-00175
This also includes the first of it's kind external IO board as specified here:
http://wasatchdevices.com/wp-content/uploads/2016/08/OEM-API-Specification.pdf

**Comment by NathanHarrington** [comment]
Physical connections:
<a href="https://ibb.co/jmOnNF"><img src="https://preview.ibb.co/drRVba/Trigger_test_setup.png" alt="Trigger_test_setup" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'></a><br />

Software setup
git clone https://github.com/WasatchPhotonics/WasatchUSB
cd WasatchUSB
python setup.py develop


Software run
python -u scripts/arm_trigger.py
Sets trigger source to zero, gets one spectra
Sleeps 1 second
Sets trigger source to one, gets one spectra
Waits 60 seconds or until data is received

Go to phidget control panel, toggle +5V on the analog output repeatedly

Results on both Linux and Windows are the same, only linux is shown
below:




wasatchusb.feature_identification CRITICAL SEND Problem with ctrl
transfer: [Errno 5] Input/Output Error
SEND Problem with ctrl transfer: [Errno 5] Input/Output Error

+968  █
      █
      █▄
      ██
      ██▂
      ███
      ███
      ███▇█▃
      ██████▆▂▂▂
+93   ██████████▇▆ ▅▄▅▃▂▅▅▂ ▃▄▂▅▄▃ ▂▂▃▂▅▂▃▃▂▃▃▃▃▃▃▃▂▂▂▂▂▃▂▃▄▂▃▄▃▄▂▃▂▂▃▂▃▄▃▂▂▃▃
wasatchusb.feature_identification CRITICAL SEND Problem with ctrl
transfer: [Errno 5] Input/Output Error
SEND Problem with ctrl transfer: [Errno 5] Input/Output Error

​
​The first critical send error message is during the set  to internal trigger.
The acquisition then proceeds normally (the spectra is noise, with no detector)
The second critical send error mesage is during the set to external trigger


Sixty seconds later:
Traceback (most recent call last): File "scripts/arm_trigger.py", line 96, in print_data(device) File "scripts/arm_trigger.py", line 64, in print_data data = device.get_line() File "/home/nharrington/projects/WasatchUSB/wasatchusb/feature_identification.py", line 325, in get_line data = self.device.read(0x82, line_buffer, timeout=USB_TIMEOUT) File "/home/nharrington/miniconda2/lib/python2.7/site-packages/pyusb-1.0.0-py2.7.egg/usb/core.py", line 988, in read File "/home/nharrington/miniconda2/lib/python2.7/site-packages/pyusb-1.0.0-py2.7.egg/usb/backend/libusb1.py", line 833, in bulk_read File "/home/nharrington/miniconda2/lib/python2.7/site-packages/pyusb-1.0.0-py2.7.egg/usb/backend/libusb1.py", line 936, in __read File "/home/nharrington/miniconda2/lib/python2.7/site-packages/pyusb-1.0.0-py2.7.egg/usb/backend/libusb1.py", line 595, in _check usb.core.USBError: [Errno 110] Operation timed out

**Comment by NathanHarrington** [comment]
The ARM board is configured to support external triggering by default. It does not support the setting of the external triggering opcode. The problem as described above was because we were setting the external trigger opcode on the arm board. This caused it to wait until timeout, regardless of external trigger events. 

The correct mechanism for using the ARM board is to store the external triggering state at a higher logic level, and do not send the CMD_GET_IMAGE opcode when acquiring externally. For comparison, the logic flow for ARM board internal is:
set internal trigger mode
get a line of data
    send CMD_GET_IMAGE
    read from bulk end point

The logic flow for ARM board external trigger is:
set external trigger mode
get a line of data
   Do not send CMD_GET_IMAGE (only for ARM board)
   read from bulk end point

This is done in the wasatchusb project by commit 51bee71326d619b9b8e7141d1cd3b8375dce742f
